source 'https://rubygems.org'

gem 'rake'

group :test do
  gem 'cucumber'
  gem 'rspec-expectations'
  gem 'rspec'
  gem 'capybara'
  gem 'selenium-webdriver', '2.46.2'
  gem 'poltergeist'
  gem 'launchy'
  gem 'rest-client'
end
